version: "3.4"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - ganache
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongo:27017/crowdfunding
      PORT: 3000
  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
