
POST http://localhost:3000/raiser/new HTTP/1.1
content-type: application/json

{
        "raiser": {
        "id": "34534534",
        "name": "aabbbccc",
        "password": "String",
        "description": "",
        "contactInfo": "String",
        "profileImage": "",
        "crowdFundsIds": [],
        "address": "0x99989b2DdEF1E3dfC6873A23eF7196e7550E1A05"
        }
}

###
POST http://localhost:3000/crowdfund/new HTTP/1.1
content-type: application/json

{
        "crowdFund": {
        "id": "122234353645",
        "state": 1,
        "title": "fff",
        "description": "String",
        "receiverDescription": "sad",
        "goalAmount": "1231",
        "deadline": 342342342,
        "images": [""],
        "resultImages": [""],
        "resultComments": "String",
        "contractAddress": "",
        "receiverAddress": "0xf9252B3c5107FEeFdbB79E37C63467a969384BeD",
        "idOfRaiser": "34534534"
        },
        "raiser": {
        "id": "34534534",
        "name": "aabbbccc",
        "password": "String",
        "description": "",
        "contactInfo": "String",
        "profileImage": "",
        "crowdFundsIds": [],
        "address": "0x99989b2DdEF1E3dfC6873A23eF7196e7550E1A05"
        }
}

###

GET http://localhost:3000/crowdfund/get HTTP/1.1