
POST http://localhost:3000/raiser/new HTTP/1.1
content-type: application/json

{
    "raiser":
    {
   "id": "12312313",
   "name": "AgenteX",
   "description": "crackocaine",
   "contactInfo": "a la vuelta de la quebrada",
   "profileImage": "la mas fachera",
   "crowdFundsIds": [],
   "address": "0xac8607F790A511E17198DD5eFdAcfEBc469d9571"
    },
    "password":"fa3igfb84rb380f3"
}

###

POST http://localhost:3000/crowdfund/new HTTP/1.1
content-type: application/json

{
    "crowdFund": {
    "id": "15824",
    "active": true,
    "title": "hola",
    "description": "capos",
    "receiverDescription": "altos locos",
    "goalAmount": "0.1",
    "deadline": 32478234,
    "images": [],
    "resultImages": [],
    "resultComments": "hoadf ",
    "receiverAddress": "0x8e884Ab5E50eFe51a9E1694398a04998A608ed6B",
    "idOfRaiser": "12312313"
    },
    "raiser": {
    "id": "12312313",
   "name": "AgenteX",
   "description": "crackocaine",
   "contactInfo": "a la vuelta de la quebrada",
   "profileImage": "la mas fachera",
   "crowdFundsIds": [],
   "address": "0xac8607F790A511E17198DD5eFdAcfEBc469d9571"
    }
}
